# Generated by Django 3.0.3 on 2020-06-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborateModel',
            fields=[
                ('userId', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('workDuring', models.CharField(max_length=512)),
                ('otherWorkDuring', models.CharField(max_length=512)),
                ('workWith', models.CharField(max_length=512)),
                ('communicateOver', models.CharField(max_length=512)),
                ('communicateWith', models.CharField(max_length=512)),
                ('workBy', models.CharField(max_length=512)),
                ('otherWorkBy', models.CharField(max_length=512)),
                ('workHours', models.CharField(max_length=512)),
                ('otherWorkHours', models.CharField(max_length=512)),
                ('projectDuration', models.CharField(max_length=512)),
            ],
        ),
    ]
