# Generated by Django 3.0.3 on 2020-06-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('projectId', models.AutoField(primary_key=True, serialize=False)),
                ('projectTitle', models.CharField(max_length=512)),
                ('projectLink', models.CharField(max_length=512)),
                ('about', models.CharField(max_length=512)),
                ('primaryTrack', models.CharField(max_length=512)),
                ('userID', models.CharField(max_length=512)),
            ],
        ),
    ]
