# Generated by Django 3.0.3 on 2020-06-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_projectmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='userID',
            new_name='userId',
        ),
    ]
