# Generated by Django 3.0.8 on 2020-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('suggestionId', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.IntegerField()),
                ('category', models.CharField(max_length=512)),
                ('message', models.CharField(max_length=512)),
            ],
        ),
    ]
