# Generated by Django 3.0.8 on 2020-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0005_suggestionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePublisher', models.CharField(max_length=512)),
                ('primaryTrack', models.CharField(max_length=512)),
                ('userId', models.CharField(max_length=512)),
            ],
        ),
    ]
