# Generated by Django 3.0.8 on 2020-08-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_auto_20200818_0805'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountModel',
            new_name='MeAccountModel',
        ),
    ]
