# Generated by Django 3.0.8 on 2020-08-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_auto_20200818_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meaccountmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='meaccountmodel',
            name='userId',
            field=models.CharField(max_length=512, primary_key=True, serialize=False),
        ),
    ]
